---
kind: Template
apiVersion: v1
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app.kubernetes.io/name: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    selector:
      matchLabels:
        app: nginx
    minReadySeconds: 5
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: bitnami/nginx:1.16-centos-7
          ports:
          - containerPort: 80
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app.kubernetes.io/name: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
    selector:
      app: nginx
parameters:
- name: APP_NAME
